# Variables
@baseUrl= http://localhost:3333

# Health check
GET {{baseUrl}}/health

###

# Get Rooms
# @name GetRoom
GET {{baseUrl}}/rooms

###

# Create Room
# @name createRoom
POST {{baseUrl}}/rooms
Accept: application/json
Content-Type: application/json

{
    "name": "Sala 1",
    "description": "Esta é a sala 1"
}

###

@roomId = {{createRoom.response.body.$.roomId}}

###

# Get Rooms Questions
# @name GetQuestion
GET {{baseUrl}}/rooms/{{roomId}}/questions

### 
# @name createQuestion
POST {{baseUrl}}/rooms/{{roomId}}/questions
Accept: application/json
Content-Type: application/json

{
    "question":"O que é clean code?"    
}

### 

# @name createQuestion
POST {{baseUrl}}/rooms/bf834c36-97ed-4a1f-9598-773b0399d379/questions
Accept: application/json
Content-Type: application/json

{
    "question":"O que é vue.js e a sua diferença em relação ao Angular?"    
}
